/* Copyright (c) 2011 European Bioinformatics Institute and Cold Spring Harbor Laboratory. */

package org.gk.sbml.model.elements;

import org.gk.sbml.NotesBuilder;
import org.gk.sbml.Utils;


/**
 * Document creating singleton.  Exists because libSBML needs to use JNI to connect to a C++
 * library.  For other SBML libraries, it may be a bit redundant, but will still
 * exist in skeletal form.
 * 
 * @author David Croft
 *
 */
public abstract class DocumentSingleton {
	protected static Document document = null;

	public DocumentSingleton() {
		super();
	}

	public Document getDocument(int level, int version) {
		System.err.println("DocumentSingleton.setLevelAndVersion: level=" + level + ", version=" + version);
		if (document == null) {
			document = createNewDocument(level, version);
			document.setNotes(NotesBuilder.createNotesString("Autogenerated from Reactome data"));
		} else
			document.setLevelAndVersion(level, version);
		
		return document;
	}
	
	// You can't create static abstract methods with Java (I don't know why).
	// But if the user doesn't overwrite this method, the code will break
	// very quickly.
	public Document createNewDocument(int level, int version) {
		return null;
	}
}
