package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.RDFSLiteral;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#biochemicalReaction
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface BiochemicalReaction extends Conversion {

    // Property http://www.biopax.org/release/biopax-level2.owl#DELTA-G

    Collection getDELTA_G();

    RDFProperty getDELTA_GProperty();

    boolean hasDELTA_G();

    Iterator listDELTA_G();

    void addDELTA_G(RDFSLiteral newDELTA_G);

    void removeDELTA_G(RDFSLiteral oldDELTA_G);

    void setDELTA_G(Collection newDELTA_G);


    // Property http://www.biopax.org/release/biopax-level2.owl#DELTA-H

    Collection getDELTA_H();

    RDFProperty getDELTA_HProperty();

    boolean hasDELTA_H();

    Iterator listDELTA_H();

    void addDELTA_H(RDFSLiteral newDELTA_H);

    void removeDELTA_H(RDFSLiteral oldDELTA_H);

    void setDELTA_H(Collection newDELTA_H);


    // Property http://www.biopax.org/release/biopax-level2.owl#DELTA-S

    Collection getDELTA_S();

    RDFProperty getDELTA_SProperty();

    boolean hasDELTA_S();

    Iterator listDELTA_S();

    void addDELTA_S(RDFSLiteral newDELTA_S);

    void removeDELTA_S(RDFSLiteral oldDELTA_S);

    void setDELTA_S(Collection newDELTA_S);


    // Property http://www.biopax.org/release/biopax-level2.owl#EC-NUMBER

    Collection getEC_NUMBER();

    RDFProperty getEC_NUMBERProperty();

    boolean hasEC_NUMBER();

    Iterator listEC_NUMBER();

    void addEC_NUMBER(String newEC_NUMBER);

    void removeEC_NUMBER(String oldEC_NUMBER);

    void setEC_NUMBER(Collection newEC_NUMBER);


    // Property http://www.biopax.org/release/biopax-level2.owl#KEQ

    Collection getKEQ();

    RDFProperty getKEQProperty();

    boolean hasKEQ();

    Iterator listKEQ();

    void addKEQ(RDFSLiteral newKEQ);

    void removeKEQ(RDFSLiteral oldKEQ);

    void setKEQ(Collection newKEQ);
}
