package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#bioSource
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface BioSource extends ExternalReferenceUtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#CELLTYPE

    OpenControlledVocabulary getCELLTYPE();

    RDFProperty getCELLTYPEProperty();

    boolean hasCELLTYPE();

    void setCELLTYPE(OpenControlledVocabulary newCELLTYPE);


    // Property http://www.biopax.org/release/biopax-level2.owl#NAME

    String getNAME();

    RDFProperty getNAMEProperty();

    boolean hasNAME();

    void setNAME(String newNAME);


    // Property http://www.biopax.org/release/biopax-level2.owl#TAXON-XREF

    Xref getTAXON_XREF();

    RDFProperty getTAXON_XREFProperty();

    boolean hasTAXON_XREF();

    void setTAXON_XREF(Xref newTAXON_XREF);


    // Property http://www.biopax.org/release/biopax-level2.owl#TISSUE

    OpenControlledVocabulary getTISSUE();

    RDFProperty getTISSUEProperty();

    boolean hasTISSUE();

    void setTISSUE(OpenControlledVocabulary newTISSUE);
}
