package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#catalysis
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Catalysis extends Control {

    // Property http://www.biopax.org/release/biopax-level2.owl#COFACTOR

    Collection getCOFACTOR();

    RDFProperty getCOFACTORProperty();

    boolean hasCOFACTOR();

    Iterator listCOFACTOR();

    void addCOFACTOR(PhysicalEntityParticipant newCOFACTOR);

    void removeCOFACTOR(PhysicalEntityParticipant oldCOFACTOR);

    void setCOFACTOR(Collection newCOFACTOR);


    // Property http://www.biopax.org/release/biopax-level2.owl#DIRECTION

    Object getDIRECTION();

    RDFProperty getDIRECTIONProperty();

    boolean hasDIRECTION();

    void setDIRECTION(Object newDIRECTION);
}
