package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#chemicalStructure
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface ChemicalStructure extends UtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#STRUCTURE-DATA

    String getSTRUCTURE_DATA();

    RDFProperty getSTRUCTURE_DATAProperty();

    boolean hasSTRUCTURE_DATA();

    void setSTRUCTURE_DATA(String newSTRUCTURE_DATA);


    // Property http://www.biopax.org/release/biopax-level2.owl#STRUCTURE-FORMAT

    Object getSTRUCTURE_FORMAT();

    RDFProperty getSTRUCTURE_FORMATProperty();

    boolean hasSTRUCTURE_FORMAT();

    void setSTRUCTURE_FORMAT(Object newSTRUCTURE_FORMAT);
}
