package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#complex
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Complex extends PhysicalEntity {

    // Property http://www.biopax.org/release/biopax-level2.owl#COMPONENTS

    Collection getCOMPONENTS();

    RDFProperty getCOMPONENTSProperty();

    boolean hasCOMPONENTS();

    Iterator listCOMPONENTS();

    void addCOMPONENTS(PhysicalEntityParticipant newCOMPONENTS);

    void removeCOMPONENTS(PhysicalEntityParticipant oldCOMPONENTS);

    void setCOMPONENTS(Collection newCOMPONENTS);


    // Property http://www.biopax.org/release/biopax-level2.owl#ORGANISM

    Collection getORGANISM();

    RDFProperty getORGANISMProperty();

    boolean hasORGANISM();

    Iterator listORGANISM();

    void addORGANISM(BioSource newORGANISM);

    void removeORGANISM(BioSource oldORGANISM);

    void setORGANISM(Collection newORGANISM);
}
