package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#confidence
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Confidence extends UtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#CONFIDENCE-VALUE

    String getCONFIDENCE_VALUE();

    RDFProperty getCONFIDENCE_VALUEProperty();

    boolean hasCONFIDENCE_VALUE();

    void setCONFIDENCE_VALUE(String newCONFIDENCE_VALUE);


    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    Collection getXREF();

    RDFProperty getXREFProperty();

    boolean hasXREF();

    Iterator listXREF();

    void addXREF(Xref newXREF);

    void removeXREF(Xref oldXREF);

    void setXREF(Collection newXREF);
}
