package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#control
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Control extends PhysicalInteraction {

    // Property http://www.biopax.org/release/biopax-level2.owl#CONTROLLED

    Collection getCONTROLLED();

    RDFProperty getCONTROLLEDProperty();

    boolean hasCONTROLLED();

    Iterator listCONTROLLED();

    void addCONTROLLED(Object newCONTROLLED);

    void removeCONTROLLED(Object oldCONTROLLED);

    void setCONTROLLED(Collection newCONTROLLED);


    // Property http://www.biopax.org/release/biopax-level2.owl#CONTROLLER

    Collection getCONTROLLER();

    RDFProperty getCONTROLLERProperty();

    boolean hasCONTROLLER();

    Iterator listCONTROLLER();

    void addCONTROLLER(PhysicalEntityParticipant newCONTROLLER);

    void removeCONTROLLER(PhysicalEntityParticipant oldCONTROLLER);

    void setCONTROLLER(Collection newCONTROLLER);


    // Property http://www.biopax.org/release/biopax-level2.owl#CONTROL-TYPE

    Object getCONTROL_TYPE();

    RDFProperty getCONTROL_TYPEProperty();

    boolean hasCONTROL_TYPE();

    void setCONTROL_TYPE(Object newCONTROL_TYPE);
}
