package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#dataSource
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface DataSource extends ExternalReferenceUtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#NAME

    Collection getNAME();

    RDFProperty getNAMEProperty();

    boolean hasNAME();

    Iterator listNAME();

    void addNAME(String newNAME);

    void removeNAME(String oldNAME);

    void setNAME(Collection newNAME);


    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    Collection getXREF();

    RDFProperty getXREFProperty();

    boolean hasXREF();

    Iterator listXREF();

    void addXREF(Xref newXREF);

    void removeXREF(Xref oldXREF);

    void setXREF(Collection newXREF);
}
