package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.OWLIndividual;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#entity
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Entity extends OWLIndividual {

    // Property http://www.biopax.org/release/biopax-level2.owl#AVAILABILITY

    Collection getAVAILABILITY();

    RDFProperty getAVAILABILITYProperty();

    boolean hasAVAILABILITY();

    Iterator listAVAILABILITY();

    void addAVAILABILITY(String newAVAILABILITY);

    void removeAVAILABILITY(String oldAVAILABILITY);

    void setAVAILABILITY(Collection newAVAILABILITY);


    // Property http://www.biopax.org/release/biopax-level2.owl#COMMENT

    Collection getCOMMENT();

    RDFProperty getCOMMENTProperty();

    boolean hasCOMMENT();

    Iterator listCOMMENT();

    void addCOMMENT(String newCOMMENT);

    void removeCOMMENT(String oldCOMMENT);

    void setCOMMENT(Collection newCOMMENT);


    // Property http://www.biopax.org/release/biopax-level2.owl#DATA-SOURCE

    Collection getDATA_SOURCE();

    RDFProperty getDATA_SOURCEProperty();

    boolean hasDATA_SOURCE();

    Iterator listDATA_SOURCE();

    void addDATA_SOURCE(DataSource newDATA_SOURCE);

    void removeDATA_SOURCE(DataSource oldDATA_SOURCE);

    void setDATA_SOURCE(Collection newDATA_SOURCE);


    // Property http://www.biopax.org/release/biopax-level2.owl#NAME

    String getNAME();

    RDFProperty getNAMEProperty();

    boolean hasNAME();

    void setNAME(String newNAME);


    // Property http://www.biopax.org/release/biopax-level2.owl#SHORT-NAME

    String getSHORT_NAME();

    RDFProperty getSHORT_NAMEProperty();

    boolean hasSHORT_NAME();

    void setSHORT_NAME(String newSHORT_NAME);


    // Property http://www.biopax.org/release/biopax-level2.owl#SYNONYMS

    Collection getSYNONYMS();

    RDFProperty getSYNONYMSProperty();

    boolean hasSYNONYMS();

    Iterator listSYNONYMS();

    void addSYNONYMS(String newSYNONYMS);

    void removeSYNONYMS(String oldSYNONYMS);

    void setSYNONYMS(Collection newSYNONYMS);


    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    Collection getXREF();

    RDFProperty getXREFProperty();

    boolean hasXREF();

    Iterator listXREF();

    void addXREF(Xref newXREF);

    void removeXREF(Xref oldXREF);

    void setXREF(Collection newXREF);
}
