package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#evidence
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Evidence extends UtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#CONFIDENCE

    Collection getCONFIDENCE();

    RDFProperty getCONFIDENCEProperty();

    boolean hasCONFIDENCE();

    Iterator listCONFIDENCE();

    void addCONFIDENCE(Confidence newCONFIDENCE);

    void removeCONFIDENCE(Confidence oldCONFIDENCE);

    void setCONFIDENCE(Collection newCONFIDENCE);


    // Property http://www.biopax.org/release/biopax-level2.owl#EVIDENCE-CODE

    Collection getEVIDENCE_CODE();

    RDFProperty getEVIDENCE_CODEProperty();

    boolean hasEVIDENCE_CODE();

    Iterator listEVIDENCE_CODE();

    void addEVIDENCE_CODE(OpenControlledVocabulary newEVIDENCE_CODE);

    void removeEVIDENCE_CODE(OpenControlledVocabulary oldEVIDENCE_CODE);

    void setEVIDENCE_CODE(Collection newEVIDENCE_CODE);


    // Property http://www.biopax.org/release/biopax-level2.owl#EXPERIMENTAL-FORM

    Collection getEXPERIMENTAL_FORM();

    RDFProperty getEXPERIMENTAL_FORMProperty();

    boolean hasEXPERIMENTAL_FORM();

    Iterator listEXPERIMENTAL_FORM();

    void addEXPERIMENTAL_FORM(ExperimentalForm newEXPERIMENTAL_FORM);

    void removeEXPERIMENTAL_FORM(ExperimentalForm oldEXPERIMENTAL_FORM);

    void setEXPERIMENTAL_FORM(Collection newEXPERIMENTAL_FORM);


    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    Collection getXREF();

    RDFProperty getXREFProperty();

    boolean hasXREF();

    Iterator listXREF();

    void addXREF(Xref newXREF);

    void removeXREF(Xref oldXREF);

    void setXREF(Collection newXREF);
}
