package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#experimentalForm
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface ExperimentalForm extends UtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#EXPERIMENTAL-FORM-TYPE

    OpenControlledVocabulary getEXPERIMENTAL_FORM_TYPE();

    RDFProperty getEXPERIMENTAL_FORM_TYPEProperty();

    boolean hasEXPERIMENTAL_FORM_TYPE();

    void setEXPERIMENTAL_FORM_TYPE(OpenControlledVocabulary newEXPERIMENTAL_FORM_TYPE);


    // Property http://www.biopax.org/release/biopax-level2.owl#PARTICIPANT

    PhysicalEntityParticipant getPARTICIPANT();

    RDFProperty getPARTICIPANTProperty();

    boolean hasPARTICIPANT();

    void setPARTICIPANT(PhysicalEntityParticipant newPARTICIPANT);
}
