package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#interaction
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Interaction extends Entity {

    // Property http://www.biopax.org/release/biopax-level2.owl#EVIDENCE

    Collection getEVIDENCE();

    RDFProperty getEVIDENCEProperty();

    boolean hasEVIDENCE();

    Iterator listEVIDENCE();

    void addEVIDENCE(Evidence newEVIDENCE);

    void removeEVIDENCE(Evidence oldEVIDENCE);

    void setEVIDENCE(Collection newEVIDENCE);


    // Property http://www.biopax.org/release/biopax-level2.owl#PARTICIPANTS

    Collection getPARTICIPANTS();

    RDFProperty getPARTICIPANTSProperty();

    boolean hasPARTICIPANTS();

    Iterator listPARTICIPANTS();

    void addPARTICIPANTS(Object newPARTICIPANTS);

    void removePARTICIPANTS(Object oldPARTICIPANTS);

    void setPARTICIPANTS(Collection newPARTICIPANTS);
}
