package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#pathway
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Pathway extends Entity {

    // Property http://www.biopax.org/release/biopax-level2.owl#EVIDENCE

    Collection getEVIDENCE();

    RDFProperty getEVIDENCEProperty();

    boolean hasEVIDENCE();

    Iterator listEVIDENCE();

    void addEVIDENCE(Evidence newEVIDENCE);

    void removeEVIDENCE(Evidence oldEVIDENCE);

    void setEVIDENCE(Collection newEVIDENCE);


    // Property http://www.biopax.org/release/biopax-level2.owl#ORGANISM

    BioSource getORGANISM();

    RDFProperty getORGANISMProperty();

    boolean hasORGANISM();

    void setORGANISM(BioSource newORGANISM);


    // Property http://www.biopax.org/release/biopax-level2.owl#PATHWAY-COMPONENTS

    Collection getPATHWAY_COMPONENTS();

    RDFProperty getPATHWAY_COMPONENTSProperty();

    boolean hasPATHWAY_COMPONENTS();

    Iterator listPATHWAY_COMPONENTS();

    void addPATHWAY_COMPONENTS(Object newPATHWAY_COMPONENTS);

    void removePATHWAY_COMPONENTS(Object oldPATHWAY_COMPONENTS);

    void setPATHWAY_COMPONENTS(Collection newPATHWAY_COMPONENTS);
}
