package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#pathwayStep
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface PathwayStep extends UtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#NEXT-STEP

    Collection getNEXT_STEP();

    RDFProperty getNEXT_STEPProperty();

    boolean hasNEXT_STEP();

    Iterator listNEXT_STEP();

    void addNEXT_STEP(PathwayStep newNEXT_STEP);

    void removeNEXT_STEP(PathwayStep oldNEXT_STEP);

    void setNEXT_STEP(Collection newNEXT_STEP);


    // Property http://www.biopax.org/release/biopax-level2.owl#STEP-INTERACTIONS

    Collection getSTEP_INTERACTIONS();

    RDFProperty getSTEP_INTERACTIONSProperty();

    boolean hasSTEP_INTERACTIONS();

    Iterator listSTEP_INTERACTIONS();

    void addSTEP_INTERACTIONS(Object newSTEP_INTERACTIONS);

    void removeSTEP_INTERACTIONS(Object oldSTEP_INTERACTIONS);

    void setSTEP_INTERACTIONS(Collection newSTEP_INTERACTIONS);
}
