package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#physicalInteraction
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface PhysicalInteraction extends Interaction {

    // Property http://www.biopax.org/release/biopax-level2.owl#INTERACTION-TYPE

    Collection getINTERACTION_TYPE();

    RDFProperty getINTERACTION_TYPEProperty();

    boolean hasINTERACTION_TYPE();

    Iterator listINTERACTION_TYPE();

    void addINTERACTION_TYPE(OpenControlledVocabulary newINTERACTION_TYPE);

    void removeINTERACTION_TYPE(OpenControlledVocabulary oldINTERACTION_TYPE);

    void setINTERACTION_TYPE(Collection newINTERACTION_TYPE);
}
