package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#proteinParticipant
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface ProteinParticipant extends PhysicalEntityParticipant {

    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-FEATURE-LIST

    Collection getSEQUENCE_FEATURE_LIST();

    RDFProperty getSEQUENCE_FEATURE_LISTProperty();

    boolean hasSEQUENCE_FEATURE_LIST();

    Iterator listSEQUENCE_FEATURE_LIST();

    void addSEQUENCE_FEATURE_LIST(SequenceFeature newSEQUENCE_FEATURE_LIST);

    void removeSEQUENCE_FEATURE_LIST(SequenceFeature oldSEQUENCE_FEATURE_LIST);

    void setSEQUENCE_FEATURE_LIST(Collection newSEQUENCE_FEATURE_LIST);
}
