package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#protein
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Protein extends PhysicalEntity {

    // Property http://www.biopax.org/release/biopax-level2.owl#ORGANISM

    BioSource getORGANISM();

    RDFProperty getORGANISMProperty();

    boolean hasORGANISM();

    void setORGANISM(BioSource newORGANISM);


    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE

    String getSEQUENCE();

    RDFProperty getSEQUENCEProperty();

    boolean hasSEQUENCE();

    void setSEQUENCE(String newSEQUENCE);
}
