package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#relationshipXref
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface RelationshipXref extends Xref {

    // Property http://www.biopax.org/release/biopax-level2.owl#RELATIONSHIP-TYPE

    String getRELATIONSHIP_TYPE();

    RDFProperty getRELATIONSHIP_TYPEProperty();

    boolean hasRELATIONSHIP_TYPE();

    void setRELATIONSHIP_TYPE(String newRELATIONSHIP_TYPE);
}
