package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#sequenceFeature
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface SequenceFeature extends UtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#FEATURE-LOCATION

    Collection getFEATURE_LOCATION();

    RDFProperty getFEATURE_LOCATIONProperty();

    boolean hasFEATURE_LOCATION();

    Iterator listFEATURE_LOCATION();

    void addFEATURE_LOCATION(SequenceLocation newFEATURE_LOCATION);

    void removeFEATURE_LOCATION(SequenceLocation oldFEATURE_LOCATION);

    void setFEATURE_LOCATION(Collection newFEATURE_LOCATION);


    // Property http://www.biopax.org/release/biopax-level2.owl#FEATURE-TYPE

    OpenControlledVocabulary getFEATURE_TYPE();

    RDFProperty getFEATURE_TYPEProperty();

    boolean hasFEATURE_TYPE();

    void setFEATURE_TYPE(OpenControlledVocabulary newFEATURE_TYPE);


    // Property http://www.biopax.org/release/biopax-level2.owl#NAME

    String getNAME();

    RDFProperty getNAMEProperty();

    boolean hasNAME();

    void setNAME(String newNAME);


    // Property http://www.biopax.org/release/biopax-level2.owl#SHORT-NAME

    String getSHORT_NAME();

    RDFProperty getSHORT_NAMEProperty();

    boolean hasSHORT_NAME();

    void setSHORT_NAME(String newSHORT_NAME);


    // Property http://www.biopax.org/release/biopax-level2.owl#SYNONYMS

    Collection getSYNONYMS();

    RDFProperty getSYNONYMSProperty();

    boolean hasSYNONYMS();

    Iterator listSYNONYMS();

    void addSYNONYMS(String newSYNONYMS);

    void removeSYNONYMS(String oldSYNONYMS);

    void setSYNONYMS(Collection newSYNONYMS);


    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    Collection getXREF();

    RDFProperty getXREFProperty();

    boolean hasXREF();

    Iterator listXREF();

    void addXREF(Xref newXREF);

    void removeXREF(Xref oldXREF);

    void setXREF(Collection newXREF);
}
