package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.RDFSLiteral;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#sequenceSite
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface SequenceSite extends SequenceLocation {

    // Property http://www.biopax.org/release/biopax-level2.owl#POSITION-STATUS

    Object getPOSITION_STATUS();

    RDFProperty getPOSITION_STATUSProperty();

    boolean hasPOSITION_STATUS();

    void setPOSITION_STATUS(Object newPOSITION_STATUS);


    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-POSITION

    RDFSLiteral getSEQUENCE_POSITION();

    RDFProperty getSEQUENCE_POSITIONProperty();

    boolean hasSEQUENCE_POSITION();

    void setSEQUENCE_POSITION(RDFSLiteral newSEQUENCE_POSITION);
}
