package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#sequenceInterval
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface SequenceInterval extends SequenceLocation {

    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-INTERVAL-BEGIN

    SequenceSite getSEQUENCE_INTERVAL_BEGIN();

    RDFProperty getSEQUENCE_INTERVAL_BEGINProperty();

    boolean hasSEQUENCE_INTERVAL_BEGIN();

    void setSEQUENCE_INTERVAL_BEGIN(SequenceSite newSEQUENCE_INTERVAL_BEGIN);


    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-INTERVAL-END

    SequenceSite getSEQUENCE_INTERVAL_END();

    RDFProperty getSEQUENCE_INTERVAL_ENDProperty();

    boolean hasSEQUENCE_INTERVAL_END();

    void setSEQUENCE_INTERVAL_END(SequenceSite newSEQUENCE_INTERVAL_END);
}
