package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.RDFSLiteral;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#smallMolecule
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface SmallMolecule extends PhysicalEntity {

    // Property http://www.biopax.org/release/biopax-level2.owl#CHEMICAL-FORMULA

    String getCHEMICAL_FORMULA();

    RDFProperty getCHEMICAL_FORMULAProperty();

    boolean hasCHEMICAL_FORMULA();

    void setCHEMICAL_FORMULA(String newCHEMICAL_FORMULA);


    // Property http://www.biopax.org/release/biopax-level2.owl#MOLECULAR-WEIGHT

    RDFSLiteral getMOLECULAR_WEIGHT();

    RDFProperty getMOLECULAR_WEIGHTProperty();

    boolean hasMOLECULAR_WEIGHT();

    void setMOLECULAR_WEIGHT(RDFSLiteral newMOLECULAR_WEIGHT);


    // Property http://www.biopax.org/release/biopax-level2.owl#STRUCTURE

    Collection getSTRUCTURE();

    RDFProperty getSTRUCTUREProperty();

    boolean hasSTRUCTURE();

    Iterator listSTRUCTURE();

    void addSTRUCTURE(ChemicalStructure newSTRUCTURE);

    void removeSTRUCTURE(ChemicalStructure oldSTRUCTURE);

    void setSTRUCTURE(Collection newSTRUCTURE);
}
