package org.biopax.model;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#transportWithBiochemicalReaction
 *
 * @version generated on Mon May 23 15:40:07 EDT 2005
 */
public interface TransportWithBiochemicalReaction extends Transport {
}
