package org.biopax.model;

import java.util.Collection;
import java.util.Iterator;

import edu.stanford.smi.protegex.owl.model.OWLIndividual;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#utilityClass
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface UtilityClass extends OWLIndividual {

    // Property http://www.biopax.org/release/biopax-level2.owl#COMMENT

    Collection getCOMMENT();

    RDFProperty getCOMMENTProperty();

    boolean hasCOMMENT();

    Iterator listCOMMENT();

    void addCOMMENT(String newCOMMENT);

    void removeCOMMENT(String oldCOMMENT);

    void setCOMMENT(Collection newCOMMENT);
}
