package org.biopax.model;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#xref
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public interface Xref extends ExternalReferenceUtilityClass {

    // Property http://www.biopax.org/release/biopax-level2.owl#DB

    String getDB();

    RDFProperty getDBProperty();

    boolean hasDB();

    void setDB(String newDB);


    // Property http://www.biopax.org/release/biopax-level2.owl#DB-VERSION

    String getDB_VERSION();

    RDFProperty getDB_VERSIONProperty();

    boolean hasDB_VERSION();

    void setDB_VERSION(String newDB_VERSION);


    // Property http://www.biopax.org/release/biopax-level2.owl#ID

    String getID();

    RDFProperty getIDProperty();

    boolean hasID();

    void setID(String newID);


    // Property http://www.biopax.org/release/biopax-level2.owl#ID-VERSION

    String getID_VERSION();

    RDFProperty getID_VERSIONProperty();

    boolean hasID_VERSION();

    void setID_VERSION(String newID_VERSION);
}
