package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.PublicationXref;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.RDFSLiteral;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#publicationXref
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultpublicationXref extends Defaultxref
         implements PublicationXref {

    public DefaultpublicationXref(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultpublicationXref() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#AUTHORS

    public Collection getAUTHORS() {
        return getPropertyValues(getAUTHORSProperty());
    }


    public RDFProperty getAUTHORSProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#AUTHORS";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasAUTHORS() {
        return getPropertyValueCount(getAUTHORSProperty()) > 0;
    }


    public Iterator listAUTHORS() {
        return listPropertyValues(getAUTHORSProperty());
    }


    public void addAUTHORS(String newAUTHORS) {
        addPropertyValue(getAUTHORSProperty(), newAUTHORS);
    }


    public void removeAUTHORS(String oldAUTHORS) {
        removePropertyValue(getAUTHORSProperty(), oldAUTHORS);
    }


    public void setAUTHORS(Collection newAUTHORS) {
        setPropertyValues(getAUTHORSProperty(), newAUTHORS);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#SOURCE

    public Collection getSOURCE() {
        return getPropertyValues(getSOURCEProperty());
    }


    public RDFProperty getSOURCEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#SOURCE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSOURCE() {
        return getPropertyValueCount(getSOURCEProperty()) > 0;
    }


    public Iterator listSOURCE() {
        return listPropertyValues(getSOURCEProperty());
    }


    public void addSOURCE(String newSOURCE) {
        addPropertyValue(getSOURCEProperty(), newSOURCE);
    }


    public void removeSOURCE(String oldSOURCE) {
        removePropertyValue(getSOURCEProperty(), oldSOURCE);
    }


    public void setSOURCE(Collection newSOURCE) {
        setPropertyValues(getSOURCEProperty(), newSOURCE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#TITLE

    public String getTITLE() {
        return (String) getPropertyValue(getTITLEProperty());
    }


    public RDFProperty getTITLEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#TITLE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTITLE() {
        return getPropertyValueCount(getTITLEProperty()) > 0;
    }


    public void setTITLE(String newTITLE) {
        setPropertyValue(getTITLEProperty(), newTITLE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#URL

    public Collection getURL() {
        return getPropertyValues(getURLProperty());
    }


    public RDFProperty getURLProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#URL";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasURL() {
        return getPropertyValueCount(getURLProperty()) > 0;
    }


    public Iterator listURL() {
        return listPropertyValues(getURLProperty());
    }


    public void addURL(String newURL) {
        addPropertyValue(getURLProperty(), newURL);
    }


    public void removeURL(String oldURL) {
        removePropertyValue(getURLProperty(), oldURL);
    }


    public void setURL(Collection newURL) {
        setPropertyValues(getURLProperty(), newURL);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#YEAR

    public RDFSLiteral getYEAR() {
        return (RDFSLiteral) getPropertyValue(getYEARProperty());
    }


    public RDFProperty getYEARProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#YEAR";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasYEAR() {
        return getPropertyValueCount(getYEARProperty()) > 0;
    }


    public void setYEAR(RDFSLiteral newYEAR) {
        setPropertyValue(getYEARProperty(), newYEAR);
    }
}
