package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.Control;
import org.biopax.model.PhysicalEntityParticipant;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#control
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultcontrol extends DefaultphysicalInteraction
         implements Control {

    public Defaultcontrol(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultcontrol() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#CONTROLLED

    public Collection getCONTROLLED() {
        return getPropertyValues(getCONTROLLEDProperty());
    }


    public RDFProperty getCONTROLLEDProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#CONTROLLED";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCONTROLLED() {
        return getPropertyValueCount(getCONTROLLEDProperty()) > 0;
    }


    public Iterator listCONTROLLED() {
        return listPropertyValues(getCONTROLLEDProperty());
    }


    public void addCONTROLLED(Object newCONTROLLED) {
        addPropertyValue(getCONTROLLEDProperty(), newCONTROLLED);
    }


    public void removeCONTROLLED(Object oldCONTROLLED) {
        removePropertyValue(getCONTROLLEDProperty(), oldCONTROLLED);
    }


    public void setCONTROLLED(Collection newCONTROLLED) {
        setPropertyValues(getCONTROLLEDProperty(), newCONTROLLED);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#CONTROLLER

    public Collection getCONTROLLER() {
        return getPropertyValuesAs(getCONTROLLERProperty(), PhysicalEntityParticipant.class);
    }


    public RDFProperty getCONTROLLERProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#CONTROLLER";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCONTROLLER() {
        return getPropertyValueCount(getCONTROLLERProperty()) > 0;
    }


    public Iterator listCONTROLLER() {
        return listPropertyValuesAs(getCONTROLLERProperty(), PhysicalEntityParticipant.class);
    }


    public void addCONTROLLER(PhysicalEntityParticipant newCONTROLLER) {
        addPropertyValue(getCONTROLLERProperty(), newCONTROLLER);
    }


    public void removeCONTROLLER(PhysicalEntityParticipant oldCONTROLLER) {
        removePropertyValue(getCONTROLLERProperty(), oldCONTROLLER);
    }


    public void setCONTROLLER(Collection newCONTROLLER) {
        setPropertyValues(getCONTROLLERProperty(), newCONTROLLER);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#CONTROL-TYPE

    public Object getCONTROL_TYPE() {
        return (Object) getPropertyValue(getCONTROL_TYPEProperty());
    }


    public RDFProperty getCONTROL_TYPEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#CONTROL-TYPE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCONTROL_TYPE() {
        return getPropertyValueCount(getCONTROL_TYPEProperty()) > 0;
    }


    public void setCONTROL_TYPE(Object newCONTROL_TYPE) {
        setPropertyValue(getCONTROL_TYPEProperty(), newCONTROL_TYPE);
    }
}
