package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.BioSource;
import org.biopax.model.Complex;
import org.biopax.model.PhysicalEntityParticipant;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#complex
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultcomplex extends DefaultphysicalEntity
         implements Complex {

    public Defaultcomplex(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultcomplex() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#COMPONENTS

    public Collection getCOMPONENTS() {
        return getPropertyValuesAs(getCOMPONENTSProperty(), PhysicalEntityParticipant.class);
    }


    public RDFProperty getCOMPONENTSProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#COMPONENTS";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCOMPONENTS() {
        return getPropertyValueCount(getCOMPONENTSProperty()) > 0;
    }


    public Iterator listCOMPONENTS() {
        return listPropertyValuesAs(getCOMPONENTSProperty(), PhysicalEntityParticipant.class);
    }


    public void addCOMPONENTS(PhysicalEntityParticipant newCOMPONENTS) {
        addPropertyValue(getCOMPONENTSProperty(), newCOMPONENTS);
    }


    public void removeCOMPONENTS(PhysicalEntityParticipant oldCOMPONENTS) {
        removePropertyValue(getCOMPONENTSProperty(), oldCOMPONENTS);
    }


    public void setCOMPONENTS(Collection newCOMPONENTS) {
        setPropertyValues(getCOMPONENTSProperty(), newCOMPONENTS);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#ORGANISM

    public Collection getORGANISM() {
        return getPropertyValuesAs(getORGANISMProperty(), BioSource.class);
    }


    public RDFProperty getORGANISMProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#ORGANISM";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasORGANISM() {
        return getPropertyValueCount(getORGANISMProperty()) > 0;
    }


    public Iterator listORGANISM() {
        return listPropertyValuesAs(getORGANISMProperty(), BioSource.class);
    }


    public void addORGANISM(BioSource newORGANISM) {
        addPropertyValue(getORGANISMProperty(), newORGANISM);
    }


    public void removeORGANISM(BioSource oldORGANISM) {
        removePropertyValue(getORGANISMProperty(), oldORGANISM);
    }


    public void setORGANISM(Collection newORGANISM) {
        setPropertyValues(getORGANISMProperty(), newORGANISM);
    }
}
