package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.Evidence;
import org.biopax.model.Interaction;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#interaction
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultinteraction extends Defaultentity
         implements Interaction {

    public Defaultinteraction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultinteraction() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#EVIDENCE

    public Collection getEVIDENCE() {
        return getPropertyValuesAs(getEVIDENCEProperty(), Evidence.class);
    }


    public RDFProperty getEVIDENCEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#EVIDENCE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasEVIDENCE() {
        return getPropertyValueCount(getEVIDENCEProperty()) > 0;
    }


    public Iterator listEVIDENCE() {
        return listPropertyValuesAs(getEVIDENCEProperty(), Evidence.class);
    }


    public void addEVIDENCE(Evidence newEVIDENCE) {
        addPropertyValue(getEVIDENCEProperty(), newEVIDENCE);
    }


    public void removeEVIDENCE(Evidence oldEVIDENCE) {
        removePropertyValue(getEVIDENCEProperty(), oldEVIDENCE);
    }


    public void setEVIDENCE(Collection newEVIDENCE) {
        setPropertyValues(getEVIDENCEProperty(), newEVIDENCE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#PARTICIPANTS

    public Collection getPARTICIPANTS() {
        return getPropertyValues(getPARTICIPANTSProperty());
    }


    public RDFProperty getPARTICIPANTSProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#PARTICIPANTS";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPARTICIPANTS() {
        return getPropertyValueCount(getPARTICIPANTSProperty()) > 0;
    }


    public Iterator listPARTICIPANTS() {
        return listPropertyValues(getPARTICIPANTSProperty());
    }


    public void addPARTICIPANTS(Object newPARTICIPANTS) {
        addPropertyValue(getPARTICIPANTSProperty(), newPARTICIPANTS);
    }


    public void removePARTICIPANTS(Object oldPARTICIPANTS) {
        removePropertyValue(getPARTICIPANTSProperty(), oldPARTICIPANTS);
    }


    public void setPARTICIPANTS(Collection newPARTICIPANTS) {
        setPropertyValues(getPARTICIPANTSProperty(), newPARTICIPANTS);
    }
}
