package org.biopax.model.impl;

import org.biopax.model.BioSource;
import org.biopax.model.OpenControlledVocabulary;
import org.biopax.model.Xref;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#bioSource
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultbioSource extends DefaultexternalReferenceUtilityClass
         implements BioSource {

    public DefaultbioSource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultbioSource() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#CELLTYPE

    public OpenControlledVocabulary getCELLTYPE() {
        return (OpenControlledVocabulary) getPropertyValueAs(getCELLTYPEProperty(), OpenControlledVocabulary.class);
    }


    public RDFProperty getCELLTYPEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#CELLTYPE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCELLTYPE() {
        return getPropertyValueCount(getCELLTYPEProperty()) > 0;
    }


    public void setCELLTYPE(OpenControlledVocabulary newCELLTYPE) {
        setPropertyValue(getCELLTYPEProperty(), newCELLTYPE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#NAME

    public String getNAME() {
        return (String) getPropertyValue(getNAMEProperty());
    }


    public RDFProperty getNAMEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#NAME";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasNAME() {
        return getPropertyValueCount(getNAMEProperty()) > 0;
    }


    public void setNAME(String newNAME) {
        setPropertyValue(getNAMEProperty(), newNAME);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#TAXON-XREF

    public Xref getTAXON_XREF() {
        return (Xref) getPropertyValueAs(getTAXON_XREFProperty(), Xref.class);
    }


    public RDFProperty getTAXON_XREFProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#TAXON-XREF";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTAXON_XREF() {
        return getPropertyValueCount(getTAXON_XREFProperty()) > 0;
    }


    public void setTAXON_XREF(Xref newTAXON_XREF) {
        setPropertyValue(getTAXON_XREFProperty(), newTAXON_XREF);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#TISSUE

    public OpenControlledVocabulary getTISSUE() {
        return (OpenControlledVocabulary) getPropertyValueAs(getTISSUEProperty(), OpenControlledVocabulary.class);
    }


    public RDFProperty getTISSUEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#TISSUE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTISSUE() {
        return getPropertyValueCount(getTISSUEProperty()) > 0;
    }


    public void setTISSUE(OpenControlledVocabulary newTISSUE) {
        setPropertyValue(getTISSUEProperty(), newTISSUE);
    }
}
