package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.BioSource;
import org.biopax.model.Evidence;
import org.biopax.model.Pathway;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#pathway
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultpathway extends Defaultentity
         implements Pathway {

    public Defaultpathway(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultpathway() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#EVIDENCE

    public Collection getEVIDENCE() {
        return getPropertyValuesAs(getEVIDENCEProperty(), Evidence.class);
    }


    public RDFProperty getEVIDENCEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#EVIDENCE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasEVIDENCE() {
        return getPropertyValueCount(getEVIDENCEProperty()) > 0;
    }


    public Iterator listEVIDENCE() {
        return listPropertyValuesAs(getEVIDENCEProperty(), Evidence.class);
    }


    public void addEVIDENCE(Evidence newEVIDENCE) {
        addPropertyValue(getEVIDENCEProperty(), newEVIDENCE);
    }


    public void removeEVIDENCE(Evidence oldEVIDENCE) {
        removePropertyValue(getEVIDENCEProperty(), oldEVIDENCE);
    }


    public void setEVIDENCE(Collection newEVIDENCE) {
        setPropertyValues(getEVIDENCEProperty(), newEVIDENCE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#ORGANISM

    public BioSource getORGANISM() {
        return (BioSource) getPropertyValueAs(getORGANISMProperty(), BioSource.class);
    }


    public RDFProperty getORGANISMProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#ORGANISM";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasORGANISM() {
        return getPropertyValueCount(getORGANISMProperty()) > 0;
    }


    public void setORGANISM(BioSource newORGANISM) {
        setPropertyValue(getORGANISMProperty(), newORGANISM);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#PATHWAY-COMPONENTS

    public Collection getPATHWAY_COMPONENTS() {
        return getPropertyValues(getPATHWAY_COMPONENTSProperty());
    }


    public RDFProperty getPATHWAY_COMPONENTSProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#PATHWAY-COMPONENTS";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPATHWAY_COMPONENTS() {
        return getPropertyValueCount(getPATHWAY_COMPONENTSProperty()) > 0;
    }


    public Iterator listPATHWAY_COMPONENTS() {
        return listPropertyValues(getPATHWAY_COMPONENTSProperty());
    }


    public void addPATHWAY_COMPONENTS(Object newPATHWAY_COMPONENTS) {
        addPropertyValue(getPATHWAY_COMPONENTSProperty(), newPATHWAY_COMPONENTS);
    }


    public void removePATHWAY_COMPONENTS(Object oldPATHWAY_COMPONENTS) {
        removePropertyValue(getPATHWAY_COMPONENTSProperty(), oldPATHWAY_COMPONENTS);
    }


    public void setPATHWAY_COMPONENTS(Collection newPATHWAY_COMPONENTS) {
        setPropertyValues(getPATHWAY_COMPONENTSProperty(), newPATHWAY_COMPONENTS);
    }
}
