package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.UtilityClass;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.impl.DefaultRDFIndividual;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#utilityClass
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultutilityClass extends DefaultRDFIndividual
         implements UtilityClass {

    public DefaultutilityClass(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultutilityClass() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#COMMENT

    public Collection getCOMMENT() {
        return getPropertyValues(getCOMMENTProperty());
    }


    public RDFProperty getCOMMENTProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#COMMENT";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCOMMENT() {
        return getPropertyValueCount(getCOMMENTProperty()) > 0;
    }


    public Iterator listCOMMENT() {
        return listPropertyValues(getCOMMENTProperty());
    }


    public void addCOMMENT(String newCOMMENT) {
        addPropertyValue(getCOMMENTProperty(), newCOMMENT);
    }


    public void removeCOMMENT(String oldCOMMENT) {
        removePropertyValue(getCOMMENTProperty(), oldCOMMENT);
    }


    public void setCOMMENT(Collection newCOMMENT) {
        setPropertyValues(getCOMMENTProperty(), newCOMMENT);
    }
}
