package org.biopax.model.impl;

import org.biopax.model.SequenceLocation;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#sequenceLocation
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultsequenceLocation extends DefaultutilityClass
         implements SequenceLocation {

    public DefaultsequenceLocation(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultsequenceLocation() {
    }
}
