package org.biopax.model.impl;

import org.biopax.model.ComplexParticipant;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#complexParticipant
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultcomplexParticipant extends DefaultphysicalEntityParticipant
         implements ComplexParticipant {

    public DefaultcomplexParticipant(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultcomplexParticipant() {
    }
}
