package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.BiochemicalReaction;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.RDFSLiteral;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#biochemicalReaction
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultbiochemicalReaction extends Defaultconversion
         implements BiochemicalReaction {

    public DefaultbiochemicalReaction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultbiochemicalReaction() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#DELTA-G

    public Collection getDELTA_G() {
        return getPropertyValues(getDELTA_GProperty());
    }


    public RDFProperty getDELTA_GProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#DELTA-G";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasDELTA_G() {
        return getPropertyValueCount(getDELTA_GProperty()) > 0;
    }


    public Iterator listDELTA_G() {
        return listPropertyValues(getDELTA_GProperty());
    }


    public void addDELTA_G(RDFSLiteral newDELTA_G) {
        addPropertyValue(getDELTA_GProperty(), newDELTA_G);
    }


    public void removeDELTA_G(RDFSLiteral oldDELTA_G) {
        removePropertyValue(getDELTA_GProperty(), oldDELTA_G);
    }


    public void setDELTA_G(Collection newDELTA_G) {
        setPropertyValues(getDELTA_GProperty(), newDELTA_G);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#DELTA-H

    public Collection getDELTA_H() {
        return getPropertyValues(getDELTA_HProperty());
    }


    public RDFProperty getDELTA_HProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#DELTA-H";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasDELTA_H() {
        return getPropertyValueCount(getDELTA_HProperty()) > 0;
    }


    public Iterator listDELTA_H() {
        return listPropertyValues(getDELTA_HProperty());
    }


    public void addDELTA_H(RDFSLiteral newDELTA_H) {
        addPropertyValue(getDELTA_HProperty(), newDELTA_H);
    }


    public void removeDELTA_H(RDFSLiteral oldDELTA_H) {
        removePropertyValue(getDELTA_HProperty(), oldDELTA_H);
    }


    public void setDELTA_H(Collection newDELTA_H) {
        setPropertyValues(getDELTA_HProperty(), newDELTA_H);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#DELTA-S

    public Collection getDELTA_S() {
        return getPropertyValues(getDELTA_SProperty());
    }


    public RDFProperty getDELTA_SProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#DELTA-S";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasDELTA_S() {
        return getPropertyValueCount(getDELTA_SProperty()) > 0;
    }


    public Iterator listDELTA_S() {
        return listPropertyValues(getDELTA_SProperty());
    }


    public void addDELTA_S(RDFSLiteral newDELTA_S) {
        addPropertyValue(getDELTA_SProperty(), newDELTA_S);
    }


    public void removeDELTA_S(RDFSLiteral oldDELTA_S) {
        removePropertyValue(getDELTA_SProperty(), oldDELTA_S);
    }


    public void setDELTA_S(Collection newDELTA_S) {
        setPropertyValues(getDELTA_SProperty(), newDELTA_S);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#EC-NUMBER

    public Collection getEC_NUMBER() {
        return getPropertyValues(getEC_NUMBERProperty());
    }


    public RDFProperty getEC_NUMBERProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#EC-NUMBER";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasEC_NUMBER() {
        return getPropertyValueCount(getEC_NUMBERProperty()) > 0;
    }


    public Iterator listEC_NUMBER() {
        return listPropertyValues(getEC_NUMBERProperty());
    }


    public void addEC_NUMBER(String newEC_NUMBER) {
        addPropertyValue(getEC_NUMBERProperty(), newEC_NUMBER);
    }


    public void removeEC_NUMBER(String oldEC_NUMBER) {
        removePropertyValue(getEC_NUMBERProperty(), oldEC_NUMBER);
    }


    public void setEC_NUMBER(Collection newEC_NUMBER) {
        setPropertyValues(getEC_NUMBERProperty(), newEC_NUMBER);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#KEQ

    public Collection getKEQ() {
        return getPropertyValues(getKEQProperty());
    }


    public RDFProperty getKEQProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#KEQ";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasKEQ() {
        return getPropertyValueCount(getKEQProperty()) > 0;
    }


    public Iterator listKEQ() {
        return listPropertyValues(getKEQProperty());
    }


    public void addKEQ(RDFSLiteral newKEQ) {
        addPropertyValue(getKEQProperty(), newKEQ);
    }


    public void removeKEQ(RDFSLiteral oldKEQ) {
        removePropertyValue(getKEQProperty(), oldKEQ);
    }


    public void setKEQ(Collection newKEQ) {
        setPropertyValues(getKEQProperty(), newKEQ);
    }
}
