package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.OpenControlledVocabulary;
import org.biopax.model.Xref;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#openControlledVocabulary
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultopenControlledVocabulary extends DefaultexternalReferenceUtilityClass
         implements OpenControlledVocabulary {

    public DefaultopenControlledVocabulary(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultopenControlledVocabulary() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#TERM

    public Collection getTERM() {
        return getPropertyValues(getTERMProperty());
    }


    public RDFProperty getTERMProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#TERM";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasTERM() {
        return getPropertyValueCount(getTERMProperty()) > 0;
    }


    public Iterator listTERM() {
        return listPropertyValues(getTERMProperty());
    }


    public void addTERM(String newTERM) {
        addPropertyValue(getTERMProperty(), newTERM);
    }


    public void removeTERM(String oldTERM) {
        removePropertyValue(getTERMProperty(), oldTERM);
    }


    public void setTERM(Collection newTERM) {
        setPropertyValues(getTERMProperty(), newTERM);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    public Collection getXREF() {
        return getPropertyValuesAs(getXREFProperty(), Xref.class);
    }


    public RDFProperty getXREFProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#XREF";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasXREF() {
        return getPropertyValueCount(getXREFProperty()) > 0;
    }


    public Iterator listXREF() {
        return listPropertyValuesAs(getXREFProperty(), Xref.class);
    }


    public void addXREF(Xref newXREF) {
        addPropertyValue(getXREFProperty(), newXREF);
    }


    public void removeXREF(Xref oldXREF) {
        removePropertyValue(getXREFProperty(), oldXREF);
    }


    public void setXREF(Collection newXREF) {
        setPropertyValues(getXREFProperty(), newXREF);
    }
}
