package org.biopax.model.impl;

import org.biopax.model.SequenceSite;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.RDFSLiteral;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#sequenceSite
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultsequenceSite extends DefaultsequenceLocation
         implements SequenceSite {

    public DefaultsequenceSite(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultsequenceSite() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#POSITION-STATUS

    public Object getPOSITION_STATUS() {
        return (Object) getPropertyValue(getPOSITION_STATUSProperty());
    }


    public RDFProperty getPOSITION_STATUSProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#POSITION-STATUS";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPOSITION_STATUS() {
        return getPropertyValueCount(getPOSITION_STATUSProperty()) > 0;
    }


    public void setPOSITION_STATUS(Object newPOSITION_STATUS) {
        setPropertyValue(getPOSITION_STATUSProperty(), newPOSITION_STATUS);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-POSITION

    public RDFSLiteral getSEQUENCE_POSITION() {
        return (RDFSLiteral) getPropertyValue(getSEQUENCE_POSITIONProperty());
    }


    public RDFProperty getSEQUENCE_POSITIONProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-POSITION";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSEQUENCE_POSITION() {
        return getPropertyValueCount(getSEQUENCE_POSITIONProperty()) > 0;
    }


    public void setSEQUENCE_POSITION(RDFSLiteral newSEQUENCE_POSITION) {
        setPropertyValue(getSEQUENCE_POSITIONProperty(), newSEQUENCE_POSITION);
    }
}
