package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.OpenControlledVocabulary;
import org.biopax.model.PhysicalInteraction;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#physicalInteraction
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultphysicalInteraction extends Defaultinteraction
         implements PhysicalInteraction {

    public DefaultphysicalInteraction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultphysicalInteraction() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#INTERACTION-TYPE

    public Collection getINTERACTION_TYPE() {
        return getPropertyValuesAs(getINTERACTION_TYPEProperty(), OpenControlledVocabulary.class);
    }


    public RDFProperty getINTERACTION_TYPEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#INTERACTION-TYPE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasINTERACTION_TYPE() {
        return getPropertyValueCount(getINTERACTION_TYPEProperty()) > 0;
    }


    public Iterator listINTERACTION_TYPE() {
        return listPropertyValuesAs(getINTERACTION_TYPEProperty(), OpenControlledVocabulary.class);
    }


    public void addINTERACTION_TYPE(OpenControlledVocabulary newINTERACTION_TYPE) {
        addPropertyValue(getINTERACTION_TYPEProperty(), newINTERACTION_TYPE);
    }


    public void removeINTERACTION_TYPE(OpenControlledVocabulary oldINTERACTION_TYPE) {
        removePropertyValue(getINTERACTION_TYPEProperty(), oldINTERACTION_TYPE);
    }


    public void setINTERACTION_TYPE(Collection newINTERACTION_TYPE) {
        setPropertyValues(getINTERACTION_TYPEProperty(), newINTERACTION_TYPE);
    }
}
