package org.biopax.model.impl;

import org.biopax.model.RelationshipXref;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#relationshipXref
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultrelationshipXref extends Defaultxref
         implements RelationshipXref {

    public DefaultrelationshipXref(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultrelationshipXref() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#RELATIONSHIP-TYPE

    public String getRELATIONSHIP_TYPE() {
        return (String) getPropertyValue(getRELATIONSHIP_TYPEProperty());
    }


    public RDFProperty getRELATIONSHIP_TYPEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#RELATIONSHIP-TYPE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRELATIONSHIP_TYPE() {
        return getPropertyValueCount(getRELATIONSHIP_TYPEProperty()) > 0;
    }


    public void setRELATIONSHIP_TYPE(String newRELATIONSHIP_TYPE) {
        setPropertyValue(getRELATIONSHIP_TYPEProperty(), newRELATIONSHIP_TYPE);
    }
}
