package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.Confidence;
import org.biopax.model.Xref;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#confidence
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultconfidence extends DefaultutilityClass
         implements Confidence {

    public Defaultconfidence(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultconfidence() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#CONFIDENCE-VALUE

    public String getCONFIDENCE_VALUE() {
        return (String) getPropertyValue(getCONFIDENCE_VALUEProperty());
    }


    public RDFProperty getCONFIDENCE_VALUEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#CONFIDENCE-VALUE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCONFIDENCE_VALUE() {
        return getPropertyValueCount(getCONFIDENCE_VALUEProperty()) > 0;
    }


    public void setCONFIDENCE_VALUE(String newCONFIDENCE_VALUE) {
        setPropertyValue(getCONFIDENCE_VALUEProperty(), newCONFIDENCE_VALUE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    public Collection getXREF() {
        return getPropertyValuesAs(getXREFProperty(), Xref.class);
    }


    public RDFProperty getXREFProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#XREF";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasXREF() {
        return getPropertyValueCount(getXREFProperty()) > 0;
    }


    public Iterator listXREF() {
        return listPropertyValuesAs(getXREFProperty(), Xref.class);
    }


    public void addXREF(Xref newXREF) {
        addPropertyValue(getXREFProperty(), newXREF);
    }


    public void removeXREF(Xref oldXREF) {
        removePropertyValue(getXREFProperty(), oldXREF);
    }


    public void setXREF(Collection newXREF) {
        setPropertyValues(getXREFProperty(), newXREF);
    }
}
