package org.biopax.model.impl;

import org.biopax.model.OpenControlledVocabulary;
import org.biopax.model.PhysicalEntity;
import org.biopax.model.PhysicalEntityParticipant;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.RDFSLiteral;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#physicalEntityParticipant
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultphysicalEntityParticipant extends DefaultutilityClass
         implements PhysicalEntityParticipant {

    public DefaultphysicalEntityParticipant(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultphysicalEntityParticipant() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#CELLULAR-LOCATION

    public OpenControlledVocabulary getCELLULAR_LOCATION() {
        return (OpenControlledVocabulary) getPropertyValueAs(getCELLULAR_LOCATIONProperty(), OpenControlledVocabulary.class);
    }


    public RDFProperty getCELLULAR_LOCATIONProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#CELLULAR-LOCATION";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCELLULAR_LOCATION() {
        return getPropertyValueCount(getCELLULAR_LOCATIONProperty()) > 0;
    }


    public void setCELLULAR_LOCATION(OpenControlledVocabulary newCELLULAR_LOCATION) {
        setPropertyValue(getCELLULAR_LOCATIONProperty(), newCELLULAR_LOCATION);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#PHYSICAL-ENTITY

    public PhysicalEntity getPHYSICAL_ENTITY() {
        return (PhysicalEntity) getPropertyValueAs(getPHYSICAL_ENTITYProperty(), PhysicalEntity.class);
    }


    public RDFProperty getPHYSICAL_ENTITYProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#PHYSICAL-ENTITY";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPHYSICAL_ENTITY() {
        return getPropertyValueCount(getPHYSICAL_ENTITYProperty()) > 0;
    }


    public void setPHYSICAL_ENTITY(PhysicalEntity newPHYSICAL_ENTITY) {
        setPropertyValue(getPHYSICAL_ENTITYProperty(), newPHYSICAL_ENTITY);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#STOICHIOMETRIC-COEFFICIENT

    public RDFSLiteral getSTOICHIOMETRIC_COEFFICIENT() {
        return (RDFSLiteral) getPropertyValue(getSTOICHIOMETRIC_COEFFICIENTProperty());
    }


    public RDFProperty getSTOICHIOMETRIC_COEFFICIENTProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#STOICHIOMETRIC-COEFFICIENT";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSTOICHIOMETRIC_COEFFICIENT() {
        return getPropertyValueCount(getSTOICHIOMETRIC_COEFFICIENTProperty()) > 0;
    }


    public void setSTOICHIOMETRIC_COEFFICIENT(RDFSLiteral newSTOICHIOMETRIC_COEFFICIENT) {
        setPropertyValue(getSTOICHIOMETRIC_COEFFICIENTProperty(), newSTOICHIOMETRIC_COEFFICIENT);
    }
}
