package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.Catalysis;
import org.biopax.model.PhysicalEntityParticipant;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#catalysis
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultcatalysis extends Defaultcontrol
         implements Catalysis {

    public Defaultcatalysis(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultcatalysis() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#COFACTOR

    public Collection getCOFACTOR() {
        return getPropertyValuesAs(getCOFACTORProperty(), PhysicalEntityParticipant.class);
    }


    public RDFProperty getCOFACTORProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#COFACTOR";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCOFACTOR() {
        return getPropertyValueCount(getCOFACTORProperty()) > 0;
    }


    public Iterator listCOFACTOR() {
        return listPropertyValuesAs(getCOFACTORProperty(), PhysicalEntityParticipant.class);
    }


    public void addCOFACTOR(PhysicalEntityParticipant newCOFACTOR) {
        addPropertyValue(getCOFACTORProperty(), newCOFACTOR);
    }


    public void removeCOFACTOR(PhysicalEntityParticipant oldCOFACTOR) {
        removePropertyValue(getCOFACTORProperty(), oldCOFACTOR);
    }


    public void setCOFACTOR(Collection newCOFACTOR) {
        setPropertyValues(getCOFACTORProperty(), newCOFACTOR);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#DIRECTION

    public Object getDIRECTION() {
        return (Object) getPropertyValue(getDIRECTIONProperty());
    }


    public RDFProperty getDIRECTIONProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#DIRECTION";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasDIRECTION() {
        return getPropertyValueCount(getDIRECTIONProperty()) > 0;
    }


    public void setDIRECTION(Object newDIRECTION) {
        setPropertyValue(getDIRECTIONProperty(), newDIRECTION);
    }
}
