package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.DataSource;
import org.biopax.model.Entity;
import org.biopax.model.Xref;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import edu.stanford.smi.protegex.owl.model.impl.DefaultRDFIndividual;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#entity
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultentity extends DefaultRDFIndividual
         implements Entity {

    public Defaultentity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultentity() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#AVAILABILITY

    public Collection getAVAILABILITY() {
        return getPropertyValues(getAVAILABILITYProperty());
    }


    public RDFProperty getAVAILABILITYProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#AVAILABILITY";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasAVAILABILITY() {
        return getPropertyValueCount(getAVAILABILITYProperty()) > 0;
    }


    public Iterator listAVAILABILITY() {
        return listPropertyValues(getAVAILABILITYProperty());
    }


    public void addAVAILABILITY(String newAVAILABILITY) {
        addPropertyValue(getAVAILABILITYProperty(), newAVAILABILITY);
    }


    public void removeAVAILABILITY(String oldAVAILABILITY) {
        removePropertyValue(getAVAILABILITYProperty(), oldAVAILABILITY);
    }


    public void setAVAILABILITY(Collection newAVAILABILITY) {
        setPropertyValues(getAVAILABILITYProperty(), newAVAILABILITY);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#COMMENT

    public Collection getCOMMENT() {
        return getPropertyValues(getCOMMENTProperty());
    }


    public RDFProperty getCOMMENTProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#COMMENT";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCOMMENT() {
        return getPropertyValueCount(getCOMMENTProperty()) > 0;
    }


    public Iterator listCOMMENT() {
        return listPropertyValues(getCOMMENTProperty());
    }


    public void addCOMMENT(String newCOMMENT) {
        addPropertyValue(getCOMMENTProperty(), newCOMMENT);
    }


    public void removeCOMMENT(String oldCOMMENT) {
        removePropertyValue(getCOMMENTProperty(), oldCOMMENT);
    }


    public void setCOMMENT(Collection newCOMMENT) {
        setPropertyValues(getCOMMENTProperty(), newCOMMENT);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#DATA-SOURCE

    public Collection getDATA_SOURCE() {
        return getPropertyValuesAs(getDATA_SOURCEProperty(), DataSource.class);
    }


    public RDFProperty getDATA_SOURCEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#DATA-SOURCE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasDATA_SOURCE() {
        return getPropertyValueCount(getDATA_SOURCEProperty()) > 0;
    }


    public Iterator listDATA_SOURCE() {
        return listPropertyValuesAs(getDATA_SOURCEProperty(), DataSource.class);
    }


    public void addDATA_SOURCE(DataSource newDATA_SOURCE) {
        addPropertyValue(getDATA_SOURCEProperty(), newDATA_SOURCE);
    }


    public void removeDATA_SOURCE(DataSource oldDATA_SOURCE) {
        removePropertyValue(getDATA_SOURCEProperty(), oldDATA_SOURCE);
    }


    public void setDATA_SOURCE(Collection newDATA_SOURCE) {
        setPropertyValues(getDATA_SOURCEProperty(), newDATA_SOURCE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#NAME

    public String getNAME() {
        return (String) getPropertyValue(getNAMEProperty());
    }


    public RDFProperty getNAMEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#NAME";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasNAME() {
        return getPropertyValueCount(getNAMEProperty()) > 0;
    }


    public void setNAME(String newNAME) {
        setPropertyValue(getNAMEProperty(), newNAME);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#SHORT-NAME

    public String getSHORT_NAME() {
        return (String) getPropertyValue(getSHORT_NAMEProperty());
    }


    public RDFProperty getSHORT_NAMEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#SHORT-NAME";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSHORT_NAME() {
        return getPropertyValueCount(getSHORT_NAMEProperty()) > 0;
    }


    public void setSHORT_NAME(String newSHORT_NAME) {
        setPropertyValue(getSHORT_NAMEProperty(), newSHORT_NAME);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#SYNONYMS

    public Collection getSYNONYMS() {
        return getPropertyValues(getSYNONYMSProperty());
    }


    public RDFProperty getSYNONYMSProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#SYNONYMS";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSYNONYMS() {
        return getPropertyValueCount(getSYNONYMSProperty()) > 0;
    }


    public Iterator listSYNONYMS() {
        return listPropertyValues(getSYNONYMSProperty());
    }


    public void addSYNONYMS(String newSYNONYMS) {
        addPropertyValue(getSYNONYMSProperty(), newSYNONYMS);
    }


    public void removeSYNONYMS(String oldSYNONYMS) {
        removePropertyValue(getSYNONYMSProperty(), oldSYNONYMS);
    }


    public void setSYNONYMS(Collection newSYNONYMS) {
        setPropertyValues(getSYNONYMSProperty(), newSYNONYMS);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#XREF

    public Collection getXREF() {
        return getPropertyValuesAs(getXREFProperty(), Xref.class);
    }


    public RDFProperty getXREFProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#XREF";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasXREF() {
        return getPropertyValueCount(getXREFProperty()) > 0;
    }


    public Iterator listXREF() {
        return listPropertyValuesAs(getXREFProperty(), Xref.class);
    }


    public void addXREF(Xref newXREF) {
        addPropertyValue(getXREFProperty(), newXREF);
    }


    public void removeXREF(Xref oldXREF) {
        removePropertyValue(getXREFProperty(), oldXREF);
    }


    public void setXREF(Collection newXREF) {
        setPropertyValues(getXREFProperty(), newXREF);
    }
}
