package org.biopax.model.impl;

import java.util.Collection;
import java.util.Iterator;

import org.biopax.model.Conversion;
import org.biopax.model.PhysicalEntityParticipant;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#conversion
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultconversion extends DefaultphysicalInteraction
         implements Conversion {

    public Defaultconversion(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultconversion() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#LEFT

    public Collection getLEFT() {
        return getPropertyValuesAs(getLEFTProperty(), PhysicalEntityParticipant.class);
    }


    public RDFProperty getLEFTProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#LEFT";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasLEFT() {
        return getPropertyValueCount(getLEFTProperty()) > 0;
    }


    public Iterator listLEFT() {
        return listPropertyValuesAs(getLEFTProperty(), PhysicalEntityParticipant.class);
    }


    public void addLEFT(PhysicalEntityParticipant newLEFT) {
        addPropertyValue(getLEFTProperty(), newLEFT);
    }


    public void removeLEFT(PhysicalEntityParticipant oldLEFT) {
        removePropertyValue(getLEFTProperty(), oldLEFT);
    }


    public void setLEFT(Collection newLEFT) {
        setPropertyValues(getLEFTProperty(), newLEFT);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#RIGHT

    public Collection getRIGHT() {
        return getPropertyValuesAs(getRIGHTProperty(), PhysicalEntityParticipant.class);
    }


    public RDFProperty getRIGHTProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#RIGHT";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRIGHT() {
        return getPropertyValueCount(getRIGHTProperty()) > 0;
    }


    public Iterator listRIGHT() {
        return listPropertyValuesAs(getRIGHTProperty(), PhysicalEntityParticipant.class);
    }


    public void addRIGHT(PhysicalEntityParticipant newRIGHT) {
        addPropertyValue(getRIGHTProperty(), newRIGHT);
    }


    public void removeRIGHT(PhysicalEntityParticipant oldRIGHT) {
        removePropertyValue(getRIGHTProperty(), oldRIGHT);
    }


    public void setRIGHT(Collection newRIGHT) {
        setPropertyValues(getRIGHTProperty(), newRIGHT);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#SPONTANEOUS

    public Object getSPONTANEOUS() {
        return (Object) getPropertyValue(getSPONTANEOUSProperty());
    }


    public RDFProperty getSPONTANEOUSProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#SPONTANEOUS";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSPONTANEOUS() {
        return getPropertyValueCount(getSPONTANEOUSProperty()) > 0;
    }


    public void setSPONTANEOUS(Object newSPONTANEOUS) {
        setPropertyValue(getSPONTANEOUSProperty(), newSPONTANEOUS);
    }
}
