package org.biopax.model.impl;

import org.biopax.model.Modulation;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#modulation
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class Defaultmodulation extends Defaultcontrol
         implements Modulation {

    public Defaultmodulation(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public Defaultmodulation() {
    }
}
