package org.biopax.model.impl;

import org.biopax.model.ChemicalStructure;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#chemicalStructure
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultchemicalStructure extends DefaultutilityClass
         implements ChemicalStructure {

    public DefaultchemicalStructure(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultchemicalStructure() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#STRUCTURE-DATA

    public String getSTRUCTURE_DATA() {
        return (String) getPropertyValue(getSTRUCTURE_DATAProperty());
    }


    public RDFProperty getSTRUCTURE_DATAProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#STRUCTURE-DATA";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSTRUCTURE_DATA() {
        return getPropertyValueCount(getSTRUCTURE_DATAProperty()) > 0;
    }


    public void setSTRUCTURE_DATA(String newSTRUCTURE_DATA) {
        setPropertyValue(getSTRUCTURE_DATAProperty(), newSTRUCTURE_DATA);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#STRUCTURE-FORMAT

    public Object getSTRUCTURE_FORMAT() {
        return (Object) getPropertyValue(getSTRUCTURE_FORMATProperty());
    }


    public RDFProperty getSTRUCTURE_FORMATProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#STRUCTURE-FORMAT";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSTRUCTURE_FORMAT() {
        return getPropertyValueCount(getSTRUCTURE_FORMATProperty()) > 0;
    }


    public void setSTRUCTURE_FORMAT(Object newSTRUCTURE_FORMAT) {
        setPropertyValue(getSTRUCTURE_FORMATProperty(), newSTRUCTURE_FORMAT);
    }
}
