package org.biopax.model.impl;

import org.biopax.model.ExperimentalForm;
import org.biopax.model.OpenControlledVocabulary;
import org.biopax.model.PhysicalEntityParticipant;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#experimentalForm
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultexperimentalForm extends DefaultutilityClass
         implements ExperimentalForm {

    public DefaultexperimentalForm(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultexperimentalForm() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#EXPERIMENTAL-FORM-TYPE

    public OpenControlledVocabulary getEXPERIMENTAL_FORM_TYPE() {
        return (OpenControlledVocabulary) getPropertyValueAs(getEXPERIMENTAL_FORM_TYPEProperty(), OpenControlledVocabulary.class);
    }


    public RDFProperty getEXPERIMENTAL_FORM_TYPEProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#EXPERIMENTAL-FORM-TYPE";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasEXPERIMENTAL_FORM_TYPE() {
        return getPropertyValueCount(getEXPERIMENTAL_FORM_TYPEProperty()) > 0;
    }


    public void setEXPERIMENTAL_FORM_TYPE(OpenControlledVocabulary newEXPERIMENTAL_FORM_TYPE) {
        setPropertyValue(getEXPERIMENTAL_FORM_TYPEProperty(), newEXPERIMENTAL_FORM_TYPE);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#PARTICIPANT

    public PhysicalEntityParticipant getPARTICIPANT() {
        return (PhysicalEntityParticipant) getPropertyValueAs(getPARTICIPANTProperty(), PhysicalEntityParticipant.class);
    }


    public RDFProperty getPARTICIPANTProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#PARTICIPANT";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPARTICIPANT() {
        return getPropertyValueCount(getPARTICIPANTProperty()) > 0;
    }


    public void setPARTICIPANT(PhysicalEntityParticipant newPARTICIPANT) {
        setPropertyValue(getPARTICIPANTProperty(), newPARTICIPANT);
    }
}
