package org.biopax.model.impl;

import org.biopax.model.SequenceInterval;
import org.biopax.model.SequenceSite;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.biopax.org/release/biopax-level2.owl#sequenceInterval
 *
 * @version generated on Mon May 23 15:40:06 EDT 2005
 */
public class DefaultsequenceInterval extends DefaultsequenceLocation
         implements SequenceInterval {

    public DefaultsequenceInterval(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultsequenceInterval() {
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-INTERVAL-BEGIN

    public SequenceSite getSEQUENCE_INTERVAL_BEGIN() {
        return (SequenceSite) getPropertyValueAs(getSEQUENCE_INTERVAL_BEGINProperty(), SequenceSite.class);
    }


    public RDFProperty getSEQUENCE_INTERVAL_BEGINProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-INTERVAL-BEGIN";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSEQUENCE_INTERVAL_BEGIN() {
        return getPropertyValueCount(getSEQUENCE_INTERVAL_BEGINProperty()) > 0;
    }


    public void setSEQUENCE_INTERVAL_BEGIN(SequenceSite newSEQUENCE_INTERVAL_BEGIN) {
        setPropertyValue(getSEQUENCE_INTERVAL_BEGINProperty(), newSEQUENCE_INTERVAL_BEGIN);
    }



    // Property http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-INTERVAL-END

    public SequenceSite getSEQUENCE_INTERVAL_END() {
        return (SequenceSite) getPropertyValueAs(getSEQUENCE_INTERVAL_ENDProperty(), SequenceSite.class);
    }


    public RDFProperty getSEQUENCE_INTERVAL_ENDProperty() {
        final String uri = "http://www.biopax.org/release/biopax-level2.owl#SEQUENCE-INTERVAL-END";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSEQUENCE_INTERVAL_END() {
        return getPropertyValueCount(getSEQUENCE_INTERVAL_ENDProperty()) > 0;
    }


    public void setSEQUENCE_INTERVAL_END(SequenceSite newSEQUENCE_INTERVAL_END) {
        setPropertyValue(getSEQUENCE_INTERVAL_ENDProperty(), newSEQUENCE_INTERVAL_END);
    }
}
